DROP DATABASE if exists boston_emergency_data1;

CREATE DATABASE boston_emergency_data1;

USE boston_emergency_data1;


CREATE TABLE boston_crime_data (
	INCIDENT_NUMBER VARCHAR(255) NOT NULL,
	OFFENSE_CODE VARCHAR(255) DEFAULT NULL , 
	OFFENSE_CODE_GROUP VARCHAR(255) DEFAULT NULL, 
	OFFENSE_DESCRIPTION VARCHAR(255) DEFAULT NULL, 
	DISTRICT VARCHAR(255) DEFAULT NULL,
	REPORTING_AREA VARCHAR(255) DEFAULT NULL,
	SHOOTING VARCHAR(255) DEFAULT NULL,
	OCCURRED_ON_DATE DATETIME DEFAULT NULL,
	YEAR INT DEFAULT NULL,
	MONTH INT DEFAULT NULL,
	DAY_OF_WEEK VARCHAR(255) DEFAULT NULL,
	HOUR INT DEFAULT NULL,
	UCR_PART VARCHAR(255) DEFAULT NULL,
	STREET  VARCHAR(255) DEFAULT NULL,
	Lat FLOAT DEFAULT NULL,
	Lng FLOAT DEFAULT NULL,
	Location VARCHAR(255) DEFAULT NULL, 
	PRIMARY KEY (INCIDENT_NUMBER));



LOAD DATA LOCAL INFILE '‎⁨crime_incident_reports.csv' INTO TABLE boston_crime_data FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

CREATE TABLE boston_police_stations (
	Lng VARCHAR(255) DEFAULT NULL , 
	Lat VARCHAR(255) DEFAULT NULL, 
    STATION_NUMBER VARCHAR(255) NOT NULL,
    BLDG_ID VARCHAR(255) DEFAULT NULL,
    BID VARCHAR(255) DEFAULT NULL,
    ADDRESS VARCHAR(255) DEFAULT NULL,
    POINT_X VARCHAR(255) DEFAULT NULL,
    POINT_Y VARCHAR(255) DEFAULT NULL,
    STATION_NAME VARCHAR(255) DEFAULT NULL,
    NEIGHBOURHOOD VARCHAR(255) DEFAULT NULL,
    CITY VARCHAR(255) DEFAULT NULL,
    ZIP_CODE VARCHAR(255) DEFAULT NULL,
    FT_SQFT VARCHAR(255) DEFAULT NULL,
    STORY_HT VARCHAR(255) DEFAULT NULL,
    PARCEL_ID VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (STATION_NUMBER));

LOAD DATA LOCAL INFILE '‎Boston_Police_Stations.csv' INTO TABLE boston_police_stations FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

CREATE TABLE boston_fire_stations (
	X FLOAT NOT NULL,
	Y FLOAT NOT NULL, 
	OBJECTID_1 INT DEFAULT NULL, 
	OBJECTID INT DEFAULT NULL, 
	BFD_ID INT DEFAULT NULL,
	MAP_ID INT DEFAULT NULL,
	MAPCODE INT DEFAULT NULL,
	LOCCODE INT DEFAULT NULL,
	LOCDEPT VARCHAR(255) DEFAULT NULL,
	LOCNAME VARCHAR(255) DEFAULT NULL,
	LOCCONTACT VARCHAR(255) DEFAULT NULL,
	LOCPHONE VARCHAR(255) DEFAULT NULL,
	LOCSTNO VARCHAR(255) DEFAULT NULL,
	LOCADDR  VARCHAR(255) DEFAULT NULL,
	LOCOWNER  VARCHAR(255) DEFAULT NULL,
	LOCWARD  INT DEFAULT NULL,
	LOCPARCL INT DEFAULT NULL,
	LOCPRECT VARCHAR(255) DEFAULT NULL,
	STUDY CHAR DEFAULT NULL,
	ABOVE INT DEFAULT NULL,
	ABOVE_DESC VARCHAR(255) DEFAULT NULL,
	SOURCE VARCHAR(255) DEFAULT NULL,
	GEOADDRESS VARCHAR(255) DEFAULT NULL,
	PD VARCHAR(255) DEFAULT NULL,
	CT90 VARCHAR(255) DEFAULT NULL,
	XCOORD VARCHAR(255) DEFAULT NULL,
	YCOORD VARCHAR(255) DEFAULT NULL);

LOAD DATA LOCAL INFILE '‎Fire_Departments.csv' INTO TABLE boston_fire_stationsFIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;


CREATE TABLE fire_incident_reports (
    INCIDENT_NUMBER VARCHAR(255) NOT NULL,
    EXPOSURE_NUMBER VARCHAR(255) DEFAULT NULL,
    ALARM_DATA DATE DEFAULT NULL,
    ALARM_TIME TIME DEFAULT NULL,
    INCIDENT_TYPE VARCHAR(255) DEFAULT NULL,
    INCIDENT_DESCRIPTION VARCHAR(255) DEFAULT NULL,
    ESTIMATED_PROPERTY_LOSS VARCHAR(255) DEFAULT NULL,
    ESTIMATED_CONTENT_LOSS VARCHAR(255) DEFAULT NULL,
    DISTRICT VARCHAR(255) DEFAULT NULL,
    CITY_SELECTION VARCHAR(255) DEFAULT NULL,
    NEIGHBORHOOD VARCHAR(255) DEFAULT NULL,
    ZIP VARCHAR(255) DEFAULT NULL,
    PROPERTY_USE VARCHAR(255) DEFAULT NULL,
    PROPERTY_DESCRIPTION VARCHAR(255) DEFAULT NULL,
    STREET_NUMBER VARCHAR(255) DEFAULT NULL,
    STREET_PREFIX VARCHAR(255) DEFAULT NULL,
    STREET_NAME VARCHAR(255) DEFAULT NULL,
    STREET_SUFFIX VARCHAR(255) DEFAULT NULL,
    STREET_TYPE VARCHAR(255) DEFAULT NULL,
    ADDRESS2 VARCHAR(255) DEFAULT NULL,
    XSTREET_PREFIX VARCHAR(255) DEFAULT NULL,
    XSTREET_NAME VARCHAR(255) DEFAULT NULL,
    XSTREET_SUFFIX VARCHAR(255) DEFAULT NULL,
    XSTREET_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (INCIDENT_NUMBER));

LOAD DATA LOCAL INFILE '‎2015-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎2016-bostonfireincidentopendata-1.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎january.2017-bostonfireincidents-1.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎february.2017-bostonfireincidents-2.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎march.2017-bostonfireincidents.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎april.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎may.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎june.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎july.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎august.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎september.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎october.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎november.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎december.2017-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎january.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎february.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎march.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎april.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎may.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎june.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎july.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎august.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎september.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '‎october.2018-bostonfireincidentopendata.csv' INTO TABLE fire_incident_reports
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;




















































