DROP DATABASE IF EXISTS ChicagoEnergy;
DROP DATABASE IF EXISTS Chicago_Energy;
CREATE DATABASE IF NOT EXISTS ChicagoEnergy;
USE ChicagoEnergy;

-- initialize districts table

CREATE TABLE IF NOT EXISTS Districts(
DUMMY INT,
DISTRICT VARCHAR(128),
KWH_JANUARY_2010 INT,
KWH_FEBRUARY_2010 INT,
KWH_MARCH_2010 INT,
KWH_APRIL_2010 INT,
KWH_MAY_2010 INT,
KWH_JUNE_2010 INT,
KWH_JULY_2010 INT,
KWH_AUGUST_2010 INT,
KWH_SEPTEMBER_2010 INT,
KWH_OCTOBER_2010 INT,
KWH_NOVEMBER_2010 INT,
KWH_DECEMBER_2010 INT,
TOTAL_KWH INT,
ELECTRICITY_ACCOUNTS INT,
ZERO_KWH_ACCOUNTS INT,
THERM_JANUARY_2010 INT,
THERM_FEBRUARY_2010 INT,
THERM_MARCH_2010 INT,
THERM_APRIL_2010 INT,
THERM_MAY_2010 INT,
THERM_JUNE_2010 INT,
THERM_JULY_2010 INT,
THERM_AUGUST_2010 INT,
THERM_SEPTEMBER_2010 INT,
THERM_OCTOBER_2010 INT,
THERM_NOVEMBER_2010 INT,
THERM_DECEMBER_2010 INT,
TOTAL_THERMS INT,
GAS_ACCOUNTS INT, 
KWH_TOTAL_SQFT INT,
THERMS_TOTAL_SQFT INT,
TOTAL_POPULATION INT,
TOTAL_UNITS INT,
AVERAGE_STORIES INT,
AVERAGE_BUILDING_AGE INT,
AVERAGE_HOUSESIZE INT,
OCCUPIED_UNITS INT,
OCCUPIED_UNITS_PERCENTAGE INT,
RENTER_OCCUPIED_HOUSING_UNITS INT,
RENTER_OCCUPIED_HOUSING_PERCENTAGE INT,
PRIMARY KEY(DISTRICT)
);

-- load data into disricts table

LOAD DATA LOCAL INFILE 'Districts.csv' INTO TABLE  Districts FIELDS TERMINATED BY ',' ESCAPED BY '"' IGNORE 1 LINES;

-- initialize community areas table

CREATE TABLE IF NOT EXISTS CommunityAreas(
DUMMY INT,
COMMUNITY_AREA VARCHAR(128),
KWH_JANUARY_2010 INT,
KWH_FEBRUARY_2010 INT,
KWH_MARCH_2010 INT,
KWH_APRIL_2010 INT,
KWH_MAY_2010 INT,
KWH_JUNE_2010 INT,
KWH_JULY_2010 INT,
KWH_AUGUST_2010 INT,
KWH_SEPTEMBER_2010 INT,
KWH_OCTOBER_2010 INT,
KWH_NOVEMBER_2010 INT,
KWH_DECEMBER_2010 INT,
TOTAL_KWH INT,
ELECTRICITY_ACCOUNTS INT,
ZERO_KWH_ACCOUNTS INT,
THERM_JANUARY_2010 INT,
THERM_FEBRUARY_2010 INT,
THERM_MARCH_2010 INT,
THERM_APRIL_2010 INT,
THERM_MAY_2010 INT,
THERM_JUNE_2010 INT,
THERM_JULY_2010 INT,
THERM_AUGUST_2010 INT,
THERM_SEPTEMBER_2010 INT,
THERM_OCTOBER_2010 INT,
THERM_NOVEMBER_2010 INT,
THERM_DECEMBER_2010 INT,
TOTAL_THERMS INT,
GAS_ACCOUNTS INT,
KWH_TOTAL_SQFT INT,
THERMS_TOTAL_SQFT INT,
TOTAL_POPULATION INT,
TOTAL_UNITS INT,
AVERAGE_STORIES INT,
AVERAGE_BUILDING_AGE INT,
AVERAGE_HOUSESIZE INT,
OCCUPIED_UNITS INT,
OCCUPIED_UNITS_PERCENTAGE INT,
RENTER_OCCUPIED_HOUSING_UNITS INT,
RENTER_OCCUPIED_HOUSING_PERCENTAGE INT,
PRIMARY KEY(COMMUNITY_AREA)
);

-- load data into community area table

LOAD DATA LOCAL INFILE 'Community_Areas.csv' INTO TABLE  CommunityAreas FIELDS TERMINATED BY ',' ESCAPED BY '"' IGNORE 1 LINES;

-- Initialize Census block table

CREATE TABLE IF NOT EXISTS CensusBlocks(
DUMMY INT,
COMMUNITY_AREA_NAME VARCHAR(128),
CENSUS_BLOCK FLOAT(32),
BUILDING_TYPE VARCHAR(32),
BUILDING_SUBTYPE VARCHAR(32),
KWH_JANUARY_2010 INT,
KWH_FEBRUARY_2010 INT,
KWH_MARCH_2010 INT,
KWH_APRIL_2010 INT,
KWH_MAY_2010 INT,
KWH_JUNE_2010 INT,
KWH_JULY_2010 INT,
KWH_AUGUST_2010 INT,
KWH_SEPTEMBER_2010 INT,
KWH_OCTOBER_2010 INT,
KWH_NOVEMBER_2010 INT,
KWH_DECEMBER_2010 INT,
TOTAL_KWH INT,
ELECTRICITY_ACCOUNTS INT,
ZERO_KWH_ACCOUNTS INT,
THERM_JANUARY_2010 INT,
THERM_FEBRUARY_2010 INT,
THERM_MARCH_2010 INT,
THERM_APRIL_2010 INT,
THERM_MAY_2010 INT,
THERM_JUNE_2010 INT,
THERM_JULY_2010 INT,
THERM_AUGUST_2010 INT,
THERM_SEPTEMBER_2010 INT,
THERM_OCTOBER_2010 INT,
THERM_NOVEMBER_2010 INT,
THERM_DECEMBER_2010 INT,
TOTAL_THERMS INT,
GAS_ACCOUNTS INT,
KWH_TOTAL_SQFT INT,
THERMS_TOTAL_SQFT INT,
TOTAL_POPULATION INT,
TOTAL_UNITS INT,
AVERAGE_STORIES FLOAT(16),
AVERAGE_BUILDING_AGE FLOAT(16),
AVERAGE_HOUSESIZE FLOAT(16),
OCCUPIED_UNITS INT,
OCCUPIED_UNITS_PERCENTAGE FLOAT(16),
RENTER_OCCUPIED_HOUSING_UNITS INT,
RENTER_OCCUPIED_HOUSING_PERCENTAGE FLOAT(16),
PRIMARY KEY(CENSUS_BLOCK)
);

-- load data into census block table

LOAD DATA LOCAL INFILE 'Census_Blocks.csv' INTO TABLE  CensusBlocks FIELDS TERMINATED BY ',' ESCAPED BY '"' IGNORE 1 LINES;

-- initialize census block table
CREATE TABLE IF NOT EXISTS CBCentroid(
	ind SMALLINT,	
	Cx FLOAT,
	Cy FLOAT,
	blockID INT(15),
	PRIMARY KEY(blockID)
	);

-- load data into census block table

LOAD DATA LOCAL INFILE 'CensusCentroid.csv' INTO TABLE CBCentroid FIELDS TERMINATED BY ',' ESCAPED BY '"' IGNORE 1 LINES;

CREATE TABLE IF NOT EXISTS DistrictKey(
	ind SMALLINT,
	ComNum SMALLINT,
	ComName VARCHAR(32),
	District VARCHAR(32),
	PRIMARY KEY (ComNum)
	);

LOAD DATA LOCAL INFILE 'DistrictKey.csv' INTO TABLE DistrictKey FIELDS TERMINATED BY ',' ESCAPED BY '"' IGNORE 1 LINES;

